apiVersion: v1
kind: Service
metadata:
   name: mynginx-svc
   labels:
     app: mynginx
     version: 2.6.1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
     app: mynginx
     version: 2.6.1